import { ApiProperty } from '@nestjs/swagger';
import { TransactionCategoryEnum } from '@prisma/client';
import { Price } from '@common/price/price.dto';

export type InsightStatus = 'ok' | 'insufficient_data';
export type Tone = 'good' | 'lime' | 'info' | 'warn' | 'bad';

export class SubScoreDTO {
  @ApiProperty({ type: String })
  label: string;

  @ApiProperty({ type: Number })
  score: number;

  @ApiProperty({
    enum: ['good', 'lime', 'info', 'warn', 'bad'],
  })
  tone: Tone;

  @ApiProperty({ type: String })
  reason: string;
}

export class HealthTagDTO {
  @ApiProperty({ type: String })
  label: string;

  @ApiProperty({ enum: ['good', 'lime', 'info', 'warn', 'bad'] })
  tone: Tone;
}

export class HealthScoreResponseDTO {
  @ApiProperty({ enum: ['ok', 'insufficient_data'] })
  status: InsightStatus;

  @ApiProperty({ type: Number })
  score: number;

  @ApiProperty({ enum: ['good', 'lime', 'info', 'warn', 'bad'] })
  tone: Tone;

  @ApiProperty({ type: String })
  segment: string;

  @ApiProperty({ type: () => [SubScoreDTO] })
  subScores: SubScoreDTO[];

  @ApiProperty({ type: Number, description: 'Days of activity available' })
  daysOfData: number;

  @ApiProperty({ type: () => [HealthTagDTO] })
  tags: HealthTagDTO[];
}

export class RiskStabilityItemDTO {
  @ApiProperty({ type: String })
  label: string;

  @ApiProperty({ type: Number })
  score: number;

  @ApiProperty({ enum: ['good', 'lime', 'info', 'warn', 'bad'] })
  tone: Tone;

  @ApiProperty({ type: String })
  reason: string;
}

export class RiskStabilityResponseDTO {
  @ApiProperty({ enum: ['ok', 'insufficient_data'] })
  status: InsightStatus;

  @ApiProperty({ type: () => [RiskStabilityItemDTO] })
  items: RiskStabilityItemDTO[];

  @ApiProperty({ type: Number })
  daysOfData: number;
}

export class RecurringPatternDTO {
  @ApiProperty({ type: String })
  counterparty: string;

  @ApiProperty({ enum: ['CREDIT', 'DEBIT'] })
  direction: 'CREDIT' | 'DEBIT';

  @ApiProperty({ type: () => Price, description: 'Average amount' })
  averageAmount: Price;

  @ApiProperty({
    enum: ['WEEKLY', 'BIWEEKLY', 'MONTHLY', 'IRREGULAR'],
  })
  cadence: 'WEEKLY' | 'BIWEEKLY' | 'MONTHLY' | 'IRREGULAR';

  @ApiProperty({ type: Number })
  averageDaysBetween: number;

  @ApiProperty({ type: Number })
  occurrences: number;

  @ApiProperty({ type: Date })
  lastSeen: Date;

  @ApiProperty({ type: Date, required: false })
  nextExpected?: Date;
}

export class RecurringResponseDTO {
  @ApiProperty({ type: () => [RecurringPatternDTO] })
  patterns: RecurringPatternDTO[];
}

export class AnomalyDTO {
  @ApiProperty({ type: String })
  transactionId: string;

  @ApiProperty({ type: String })
  reference: string;

  @ApiProperty({ enum: TransactionCategoryEnum })
  category: TransactionCategoryEnum;

  @ApiProperty({ type: () => Price, description: 'Anomalous amount' })
  amount: Price;

  @ApiProperty({
    type: 'object',
    properties: {
      low: { type: () => Price },
      high: { type: () => Price },
    },
  })
  expectedRange: { low: Price; high: Price };

  @ApiProperty({ type: Number })
  zScore: number;

  @ApiProperty({ type: String })
  reason: string;

  @ApiProperty({ type: Date })
  flaggedAt: Date;
}

export class AnomaliesResponseDTO {
  @ApiProperty({ type: () => [AnomalyDTO] })
  anomalies: AnomalyDTO[];
}

export class SummaryBulletDTO {
  @ApiProperty({ enum: ['good', 'lime', 'info', 'warn', 'bad'] })
  tone: Tone;

  @ApiProperty({ type: String })
  text: string;
}

export class WeeklySummaryResponseDTO {
  @ApiProperty({ enum: ['ok', 'insufficient_data'] })
  status: InsightStatus;

  @ApiProperty({ type: () => [SummaryBulletDTO] })
  bullets: SummaryBulletDTO[];

  @ApiProperty({
    type: Boolean,
    description: 'True if the bullets were generated by Claude; false if deterministic fallback copy.',
  })
  aiGenerated: boolean;
}

export class RecommendationTagDTO {
  @ApiProperty({ type: String })
  label: string;

  @ApiProperty({ enum: ['good', 'lime', 'info', 'warn', 'bad'] })
  tone: Tone;
}

export class RecommendationDTO {
  @ApiProperty({ type: () => RecommendationTagDTO })
  tag: RecommendationTagDTO;

  @ApiProperty({ type: String })
  title: string;

  @ApiProperty({ type: String })
  detail: string;

  @ApiProperty({ type: String, description: 'Internal rule that fired' })
  trigger: string;
}

export class RecommendationsResponseDTO {
  @ApiProperty({ type: () => [RecommendationDTO] })
  recommendations: RecommendationDTO[];

  @ApiProperty({
    type: Boolean,
    description: 'True if titles/details were phrased by Claude; false if deterministic.',
  })
  aiGenerated: boolean;
}
